-- Tabla de Profesionales (Leads Scrapeados)
create table professionals (
  id bigint generated by default as identity primary key,
  name text not null,
  service_type text not null, -- 'Plomero', 'Electricista', etc.
  phone text,
  website text,
  source text default 'Google Maps',
  status text default 'NEW', -- 'NEW', 'CONTACTED', 'REGISTERED'
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabla de Finanzas (Revenue Real)
create table financial_logs (
  id bigint generated by default as identity primary key,
  amount numeric not null,
  type text not null, -- 'INCOME', 'EXPENSE'
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabla de Logs del Sistema (Para el Dashboard)
create table system_logs (
  id bigint generated by default as identity primary key,
  agent_name text not null, -- 'MARKETING', 'RECRUITER', 'FINANCE'
  message text not null,
  level text default 'INFO',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Habilitar Row Level Security (RLS) para seguridad básica
alter table professionals enable row level security;
alter table financial_logs enable row level security;
alter table system_logs enable row level security;

-- Políticas de acceso (Permitir todo por ahora para el servicio anon/service_role)
create policy "Enable all access for service role" on professionals for all using (true);
create policy "Enable all access for service role" on financial_logs for all using (true);
create policy "Enable all access for service role" on system_logs for all using (true);
