-- Agregar columnas de reputación a la tabla de profesionales
alter table professionals 
add column rating numeric default 5.0,
add column reviews_count integer default 0,
add column last_contacted_at timestamp with time zone;

-- Crear tabla de Reviews (para el futuro)
create table reviews (
  id bigint generated by default as identity primary key,
  professional_id bigint references professionals(id),
  user_id uuid references auth.users(id), -- Opcional por ahora
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Habilitar acceso
alter table reviews enable row level security;
create policy "Enable all access for service role" on reviews for all using (true);
